### PR TITLE
Add fix to allow packaging for ubuntu vivid

### LINKED ISSUE #189: debian packaging fails with vtk6 and ubuntu-vivid
when selecting the more up-to-date vtk6 to as dependency for statismo, build fails.

### PR DESCRIPTION
**Pull request by zarquon42b**
Fixes #189 . Adaption of dependencies for ubuntu vivid and a hack in the script, temporarily modifying CMakeList.txt during package creation.

### CODE REVIEW

**Comment by zarquon42b** [comment]
OK things are more complicated, as this only fixes the build of statismo, however, any software that links against statismo_VTK, needs to guess, which Qt5 libs are linked against. In this branch I added a macro to modules/VTK/src/CMakeList.txt that removes all Qt related libs from ${VTK_LIBRARIES}. What do you think about that? Should I start maintaining patches for packaging?

**Comment by arnaudgelas** [comment]
The problem is that right now, we are looking for VTK using
```cmake
find_package( VTK REQUIRED )
````

we do not make use of COMPONENTS, or do not list modules we need for statismo. So we link statismo with all vtk libraries (which definitively too much). We should only add required modules, but it would work only with vtk6...

**Comment by marcelluethi** [comment]
@arnaudgelas  From my side I have no objections against dropping support for VTK 5.x in future releases. But I don't know how many people still rely on 5.0.

**Comment by zarquon42b** [comment]
I just checked for compatibility with Ubuntu Trusty (LTS) and vtk6 from repos works here as well. So from my side dumping vtk5 is fine.

**Comment by arnaudgelas** [comment]
https://github.com/statismo/statismo/commit/2a363b3742dca91c45ff26390eed98447db454ae

**Comment by zarquon42b** [comment]
closed as arnauds approach takes also care about more selective linking

**Pull request closed without merging**
