### PR TITLE
revised README

### PR DESCRIPTION
**Pull request by marcelluethi**
Updated the README to include:
- the CLI
- Build instructions for Ubuntu / Debian
- Related projects

@zarquon42b I assumed that the deb package you provide also works on debian (not only Ubuntu). Is this correct or are there any restrictions? Do you agree with the text in the related projects page?

@arnaudgelas I somehow lost track of the status of the Redhat packages. Is it possible to install statismo on Redhat via an RPM?

Please let me know in case you think something is missing or should not be written that way.

### CODE REVIEW

**Comment by arnaudgelas** [comment]
@marcelluethi I have not had enough time to address all comments and finish the process to get the rpm in fedora... If someone is willing to take over this task, I can help, but as today I can't spend much time on  it.

For reference, here is the entry in fedora bug tracker:
https://bugzilla.redhat.com/show_bug.cgi?id=1171624

**Comment by zarquon42b** [comment]
@marcelluethi yes, you can easily build it on debian by issueing dpkg-buildpackage from within statismo's root dir. The ppa only works for Ubuntu (as far as I know, I think debian are discussing about a similar feature there). However, I have not yet looked into submitting it directly to debian upstream (we will probably write a more detailed copyright file) . If anyone is willing to sort out what would be needed to do this, I would be very grateful ;).

**Comment by marcelluethi** [comment]
@arnaudgelas @zarquon42b I will see if I can find somebody who is willing to continue on the package efforts. For me, bringing it into the official repositories does not have too high priority. 

I find it great that there are packages available, even if they cannot be downloaded from the official repositories. It is a huge improvement in convenience, compared to state of statismo before you two helped with the superbuild and the packages.

**Comment by zarquon42b** [comment]
If you want, I can build debian packages for unstable, testing and stable and we can distribute them via github website.

Best
Stefan

**Comment by zarquon42b** [comment]
For testing purposes, I set up a debian repository in my github account that provides debs for debian stable and testing (i386 and amd64). You can use it like described here: https://github.com/zarquon42b/debian/blob/gh-pages/README.md
I tested it using debian testing, please check it out.

Best
Stefan

**Pull request merged**
