### PR TITLE
Replace tmpname by boost::unique_path. Fixes #173.

### LINKED ISSUE #173: tmpname warning
Building with g++ on linux gives the following warning: 
```
.../BUILD/statismo-0.10.1/modules/core/include/StatismoUtils.h:142:
> warning: the use of `tmpnam' is dangerous, better use `mkstemp'
```
Though statismo's use of the tmpnam method should be safe, this warning is still annoying.

### PR DESCRIPTION
**Pull request by marcelluethi**
The price to pay for this fix is that we now depend also on boost::filesystem. 
However, as we already make use of several boost libraries, this does not add much new complexity.

### CODE REVIEW

**Comment by marcelluethi** [comment]
I have not tested it yet on windows.
@clangguth  can you quickly check if the build works on windows?

**Comment by clangguth** [comment]
@marcelluethi 
Hmmm... not sure if I'm doing something wrong, but the build fails:


(CustomBuild target) -> 
 j:\statismo-win-superbuild\workspace\modules\core\include\StatismoUtils.h(137): error C2440: 'initializing' : cannot convert from 'const boost::filesystem::path::string_type' to 'std::basic_string<_Elem,_Traits,_Alloc>' [C:\statismo-superbuild\Statismo-build\modules\core\src\statismo_core.vcxproj] [C:\statismo-superbuild\Statismo.vcxproj]
  j:\statismo-win-superbuild\workspace\modules\core\include\StatismoUtils.h(137): error C2440: 'initializing' : cannot convert from 'const boost::filesystem::path::string_type' to 'std::basic_string<_Elem,_Traits,_Alloc>' [C:\statismo-superbuild\Statismo-build\modules\core\src\statismo_core.vcxproj] [C:\statismo-superbuild\Statismo.vcxproj]

    565 Warning(s)
    2 Error(s)

(see https://statismo.cs.unibas.ch/jenkins/job/statismo-win-superbuild/49/console for full log)

**Comment by marcelluethi** [comment]
@clangguth It should work now (tested with VS 2010). To be on the safe side, it would be good if you could rerun jenkins also on your system.

**Comment by clangguth** [comment]
Works now, merging

**Pull request merged**
