### PR TITLE
Example for removing boost::bind from ITK wrapping.

### PR DESCRIPTION
**Pull request by tom-albrecht**
This is mainly to start a discussion. I think the use of ```boost::bind``` in the ITK wrapping is over-complicated and really unpleasant to debug. 

Its only use is to evade writing a try/catch block in every method. But I think the try/catch block is easier to read, understand, debug, and maintain than the binding in every function. This way actually duplicates less code than the boost::bind implementation. (Check for instance the number of characters in lines 106-108 below).

If we ever find ourselves in the position to do more than ```itkExceptionMacro(<< s.what());``` in the catch block, we could easily replace the ```itkExceptionMacro``` with a different macro. Of course, a macro is old-school and not functional programming, but in the current solution we use a bunch of functional programming to reduce every function to a function of void to then call a macro...

Of course this is only one file, and this would need to be done in every file for the ITK wrapping. I hope somebody is willing to help.

### CODE REVIEW

**Comment by marcelluethi** [comment]
Thanks for starting this discussion. I also don't like the code and I am very happy if somebody presents a better solution. However, the file you show is not a representative example. It is an example where the solution is overly complicated because a new object has to be generated and it contains only a few functions that need to be wrapped. 

You should also have a look at https://github.com/statismo/statismo/blob/master/modules/ITK/include/itkStatisticalModel.h , where the situation looks completely different. 

I think before we change any code we should have a good strategy how to simplify these wrappers in a consistent way. I am therefore against merging this PR.

Maybe there is an easier solution that does not involve boost::bind that achieves the same?
What do others think?

**Comment by tom-albrecht** [comment]
That's a fair point, and I agree that nothing should be merged until we found a good solution for all wrappers. I used this example because it required a manual edit of only a handful of functions. Changing ```itkStatisticalModel.h``` into this style requires a lot of manual editing and does introduce a lot more lines of code. 

A look at itkStatisticalModel.h however shows that only about half of the functions allow a one-line call like 
``` cpp
VectorType ComputeCoefficientsForDataset(DatasetConstPointerType ds) const {
        return toVnlVector(callstatismoImpl(boost::bind(&ImplType::ComputeCoefficientsForDataset, this->GetstatismoImplObj(), ds)));
    } 
```

The rest needs an additional typedef like 

``` cpp
    ValueType DrawSampleAtPoint(const VectorType& coeffs, unsigned ptid, bool addNoise  = false) const  {
        typedef ValueType (ImplType::*functype)(const statismo::VectorType&, unsigned, bool) const;
        return callstatismoImpl(boost::bind(static_cast<functype>(&ImplType::DrawSampleAtPoint), this->GetstatismoImplObj(), fromVnlVector(coeffs), ptid, addNoise));
    }
```
This is already more characters than the try/catch block. Granted, more "lines of code", but most of these lines just contain one curly brace. So I would not go as far as saying "the situation looks completely different" in this case.

A straight-forward old-school way would be to put the whole try/catch block in a macro. But maybe somebody finds a perfect solution.

A good thing about the fully explicit version I proposed is that you can easily step in and out of these functions with a debugger. And is is made transparent that in each function the statismo exceptions are caught. The actual "code" that is duplicated is really just the ```itkExceptionMacro(<< s.what());```.

**Comment by tom-albrecht** [comment]
How about this for fans of one-liners:

``` cpp
    typename StatisticalModelType::Pointer BuildNewModel(const DataItemListType& DataItemList, const PointValueWithCovarianceListType& pointValuesWithCovariance, 	double noiseVariance) {      
      StatismoStatisticalModelType* model_statismo;
      
      try {model_statismo = this->m_impl->BuildNewModel(DataItemList, pointValuesWithCovariance, noiseVariance);} catch (statismo::StatisticalModelException& s) {itkExceptionMacro(<< s.what());}
      
      typename StatisticalModelType::Pointer model_itk = StatisticalModelType::New();
      model_itk->SetstatismoImplObj(model_statismo);
      return model_itk;
    }
```

**Comment by patrikhuber** [comment]
I suspect you're already aware of it, but in general, the recommended way is to use lambdas instead of `bind`. Lambdas solve a few issues of `bind` and are also unproblematic to debug. If you're worried about compiler compatibility, IIRC Visual Studio has had basic support for lambdas since VS2010, though they were quite buggy back then. From VS2012 on the support is quite decent. In your case, the call to `bind` could easily replaced by a lambda. I'm not sure it would save the typedef though.

**Comment by tom-albrecht** [comment]
Thanks a lot for the input. Can you post a quick example? Maybe take any of the 3 examples I posted above and change it into a lambda expression?

**Comment by marcelluethi** [comment]
As this discussion touches on some fundamental issues that we will need to discuss in depth, I will move the discussion to the statismo-developers mailing list (statismo-developers@googlegroups.com) and close this pull request. Anybody who has an opinion on how to improve statismo in the future is warmly invited to join the discussion there.

**Pull request closed without merging**
