### PR TITLE
adapted travis to use ppa:zarquon42/precise-backports and libinsightt…

### LINKED ISSUE #217: Create itk4 backport for ubuntu-precise to speed up travis checks
Create backport of debian package nsighttoolkit4 for ubuntu-precise and use it to speed up travis checks.

### PR DESCRIPTION
**Pull request by zarquon42b**
…oolkit4-dev
Fixes #217 
I tested it on my fork and it works (about 10 minutes gained): https://travis-ci.org/zarquon42b/statismo/builds/67664230

### CODE REVIEW

**Comment by arnaudgelas** [comment]
@zarquon42b This is awesome!!! 

Would that be possible also to get vtk6 instead of vtk5?
Also since we would get all system librairies, there is no need to use the superbuild (we could directly use the main CMakeLists.txt)

**Comment by zarquon42b** [comment]
I tried to repackage vtk6 but this was not as simple as with itk4, as some dependencies are missing (and not available via ppa). Packaging will take more efforts. But I will look into it.

Best
Stefan

**Comment by arnaudgelas** [comment]
Stefan, it may not be worth it... At this point, the most important is that it is building faster!
Hopefully travis people are going to upgrade from ubuntu 12.04 to a more recent version soon...

**Comment by zarquon42b** [comment]
Nevermind, I played around a bit (for sports sake) and I uploaded a slightly dumbed down version of vtk6 (to avoid repackaging all dependencies => hell) that worked here (building statismo) on a VM with precise installed.
Once it has finished building (in the ppa) I will test it with travis (also skipping superbuild)
Best
Stefan

**Comment by zarquon42b** [comment]
BTW: the travis people may still need more time: https://github.com/travis-ci/travis-ci/milestones

**Comment by arnaudgelas** [comment]
perfect!!

**Pull request merged**
