### PR TITLE
[BUG] fixed correct calculation of PCAModel in case of n > p.

### LINKED ISSUE #239: develop branch: (sample size) >= (3* number of coordinates ) gives wrong variance
With the merge of  5c5a05fee23979b27dc1a86ecbaea7b9760d0f7e (@tom-albrecht introduced the memory efficient PCA), the PCA calculation gives wrong results if (sample size) >= (3* coordinate size) - e.g with large set of individuals but sparse point clouds.

### PR DESCRIPTION
**Pull request by zarquon42b**
Fixes #239

### CODE REVIEW

**Comment by tom-albrecht** [comment]
Can you do the same for the `case SelfAdjointEigenSolver`?
I.e., removing `pcaBasis /= sqrt(n - 1.0);` and adding `singularValues /= (n - 1.0);`.

**Comment by zarquon42b** [comment]
I looked ther, but The SelfAdjointEigenSolver does not account for cases n > p; so it can't be used for those cases.

**Comment by tom-albrecht** [comment]
Yes, but it still contains the same error that I introduced in 
https://github.com/statismo/statismo/pull/226/commits/4bef447b9b4f2da51dc69bb3384e3bae8ba24b9e

**Comment by tom-albrecht** [comment]
In all cases, the eigen_vectors_ contained in the `pcaBasis` are constrained to have a length of 1, so it makes no sense to multiply them by `1/n-1`.

**Comment by tom-albrecht** [comment]
It is only in the special case of n < p in which we compute the SVD of `X X^T` instead of `X^T X` that everything is a lot more complicated and the `pcaBasis `has to be rescaled at the very end.
But, in the straight-forward cases `n > p` and `SelfAdjointEigenSolver `, `pcaBasis `must stay as it is, but the eigenvalues have to be scaled correctly.

**Comment by tom-albrecht** [comment]
To be honest, if the `SelfAdjointEigenSolver `is neither used nor tested, it should be removed altogether, but this obvious mistake should be fixed in this pull request.

**Comment by zarquon42b** [comment]
Ah, yes of  course, I just realized.

**Pull request merged**
