### PR TITLE
Make compilation work for VS2015

### PR DESCRIPTION
**Pull request by marcelluethi**
These changes make statismo compile with Visual Studio 2015. 
As many of the dependencies that are used in the superbuild did not compile with VS2015, 
we also used newer versions of all the dependencies. The current version depends on 
- Eigen version 3.2.9
- Boost 1.59
- ITK 4.10
- VTK 6.3

HDF5 was dropped as an explicit dependency. Instead we use the HDF5 library that is shipped with ITK. This should resolve many compatibility problems. As a consequence, ITK is now a mandatory dependency of scalismo.

### CODE REVIEW

**Comment by zarquon42b** [comment]
Sorry, I missed the assignment, looking into it today.

**Comment by zarquon42b** [comment]
My package depending on statismo fails with `vtkStandardMeshRepresenter.h:42:23: [...] H5Cpp.h: No such file or directory`
Adding 
`include(${ITK_USE_FILE})` to my CMake file and exchanging H5Cpp.h with itk_H5Cpp.h in vtkStandardMeshRepresenter.h solves the issue.

We should probably change all references from H5Cpp.h to itk_H5Cpp.h. 
Is that a correct assumption?

**Comment by tom-albrecht** [comment]
No, I believe there is a file somewhere that redirects somehow to the ITK file. 


So instead of renaming the references, we have to make sure that file is used. 





From: Stefan Schlager

Sent: Monday, 17 October, 11:44

Subject: Re: [statismo/statismo] Make compilation work for VS2015 (#252)

To: statismo/statismo

Cc: tom-albrecht, Assign



My package depending on statismo fails with vtkStandardMeshRepresenter.h:42:23: [...] H5Cpp.h: No such file or directory

Adding 

include(${ITK_USE_FILE}) to my CMake file and exchanging H5Cpp.h with itk_H5Cpp.h in vtkStandardMeshRepresenter.h solves the issue.


We should probably change all references from H5Cpp.h to itk_H5Cpp.h. 

Is that a correct assumption?

**Comment by zarquon42b** [comment]
There is a file called itkstatismoITKConfig.h. But I think if itk-hdf5 is used,  #include <H5Cpp.h> needs to be replaced by #include <itkstatismoITKConfig.h>. But this simply inludes H5Cpp.h, so it is basically the same as replacing everything. Otherwise, the compiler will always complain about a missing file.

**Comment by marcelluethi** [comment]
@zarquon42b Thanks a lot for testing it. 

The h5cpp file can be found in ./ITK-4.10/itkhdf5/cpp 
The relevant variable, which should contain the path is```HDF5_INCLUDE_DIRS```. This variable is set in the main ```CMakeLists.txt``` and for already installed packages in ```statismoConfig.cmake```. 

Could you try if adding this path to your package script help?

**Comment by zarquon42b** [comment]
This will, however, not work for debian/ubuntu upstream package, wehere this does not exist (also it is still at version 4.9).

**Comment by zarquon42b** [comment]
This will definitely break package generation for debian/ubuntu.

**Comment by zarquon42b** [comment]
Looking at debian's insighttoolkit package code, this seems to be owed to the fact that the use system hdf5.

**Comment by zarquon42b** [comment]
worst case would be that I need to maintain my own fork with custom includes - which would be rather suboptimal.

**Comment by zarquon42b** [comment]
What would be the drawback of including itk_H5Cpp.h? As I can see, it takes care of including the same header that itk used. It contains
```#ifdef ITK_USE_SYSTEM_HDF5
# include <H5Cpp.h>
#else
# include "itkhdf5/cpp/H5Cpp.h"
#endif

```
So it will point to the right file in any case.

**Comment by marcelluethi** [comment]
@zarquon42b I think that in this case this is the best solution.

**Comment by marcelluethi** [comment]
@zarquon42b Does the packaging process involve compilation of statismo or is this done in a separate step. In the first case, we would need to make use of ```USE_EXTERNAL_HDF5``` also in our build scripts. In the latter case a good solution could be to link to hdf5 statically, such that the dependency to hdf5 can be dropped altogether.

**Comment by zarquon42b** [comment]
No, compilation involves calling cmake with the provided arguments and compilation, as the result will be a binary package. It is good practise to use as many system libraries as possible (these are usually dynamic libraries). Why is  `USE_EXTERNAL_HDF5` necessary, if we restrict hdf5 linking to the same version that is used to build ITK? In the latter case `#include <tk_H5Cpp.h>` would satisfy all cases: those users who decide to use custom configured ITK as well as those that use the one provided by the system.

**Comment by zarquon42b** [comment]
Also the `USE_EXTERNAL_HDF5` variable appends itkhdf5/cpp and the H5Cpp.h is only to be found there if ITK is not compiled against external HDF5 lib.

**Comment by tom-albrecht** [comment]
The problem is that HDF5 has been a pain since day one, and every workaround we use has come around and bite us in the behind. But in the end, we have no other choice but find another workaround for every new HDF5 obstacle we are faced with. 

 

Basically, using ITK’s version of HDF5 is one such workaround, but so far it only affected the CMake files, not the actual code. If we now start adding itk_H5Cpp.h to all files, we actually start messing with the C++ code, and it becomes harder, for instance, for people who don’t use CMake and just manually click together the dependencies in Visual Studio. These people then have to have ITK or need to rename the references back to H5Cpp.h. 

 

Then again these people probably don’t exist, and this is more of an academic consideration, but it is a little bit ugly to have itk_ includes littered around the code.

**Comment by zarquon42b** [comment]
> The problem is that HDF5 has been a pain since day one

... on windows machines ;)
But, of course, you are right about the style, however there are only 6 instances and we could use `include<statismoITKConfig.h>` instead.
Currently you cannot use `USE_EXTERNAL_HDF5` for ITK installs using system HDF5 (i.e. all linux package manager maintained versions), as they use the system's H5 headers that are located elsewhere and pointed to by itk_H5Cpp.h. So actually, this would constrain statismo installations much more than changing 6 includes. I can understand that it is easier on windows machines, but would break a lot other stuff.
My interest, to be frank, is to keep statismo as easy installable as possible (on Linux machines). At the moment I have quite a few not too technically versed users (for RvtkStatismo), and sending them 5 lines of script to install statismo as a package is very convenient. I doubt that they would manage to pull off a superbuild as easily. Also the system is not cluttered with multiple versions of ITK, HDF5 (as it is common on windows).

**Comment by tom-albrecht** [comment]
Hi Stefan,

 

Unfortunately, the pains of HDF5 have not been constrained to the Windows domain. Getting it to work with the versions of VTK, ITK, Ubuntu etc. has been a pain from day one.

 

Secondly, the “example” was based on Windows, but the same thing applies to all operating systems.

 

Thirdly, I am not really against making any of the proposed fixes. I just think we have to try to choose the workaround with the least influence. But having an Ubuntu package is priceless.

 

I think the impasse we are at currently is that an external HDF5 will not work on Windows and an internal version will not work with Ubuntu packages. So again, we have to find some kind of ugly workaround to make everybody at least semi-happy.

 

Which workaround do you prefer, Marcel?

 

Best regards

 

Tom

**Comment by zarquon42b** [comment]
Hi Tom,

> Unfortunately, the pains of HDF5 have not been constrained to the Windows domain. Getting it to work with the versions of VTK, ITK, Ubuntu etc. has been a pain from day one.

Sorry, I think I joined after you resolved these issues, my apologies.

Basically, I am happy with any solution that allows me to do the package building step by issueing an appropriate cmake argument. What I want to avoid is to maintain patches to make the packaging work.
Apart from the "ugliness", would the inclusion of `statismoITKConfig.h` or `itk_H5Cpp.h` instead of `h5Cpp.h` work on windows?

**Comment by marcelluethi** [comment]
I will need to compile it on Windows to see if it works there (I can do this tonight). If it works I have nothing against the proposed fix, as I also think that having the package is priceless. 

As soon as I find a little bit of time (hope later this week) I will try to remove any reference to HDF5 from the headers and link statically to the hdf5 libraries. I think it should be possible and would solve this issue once and for all.

**Comment by tom-albrecht** [comment]
I am currently at the MICCAI conference so I can't try it out, but both methods should work. If the files are found on Linux, they are probably in the ITK_INCLUDE_DIRS. 


I would favor an itkConfig.h, because that would be easier to change when the next HDF5 woes come around the corner. 


Actually, why don't we call the file statismo_H5cpp.h? That file could do for us what itk_H5cpp.h does for ITK, namely including a valid H5 version. 

Its purpose would be clear, and when we have to do more changes the ugliness would be constrained to that file. 

And if a user wants to use another H5 version, e.g. from VTK or Ubuntu, he would just need to edit that file. 




On Tue, Oct 18, 2016 at 6:15 PM +0300, "Marcel Luethi" <notifications@github.com> wrote:












I will need to compile it on Windows to see if it works there (I can do this tonight). If it works I have nothing against the proposed fix, as I also think that having the package is priceless. 



As soon as I find a little bit of time (hope later this week) I will try to remove any reference to HDF5 from the headers and link statically to the hdf5 libraries. I think it should be possible and would solve this issue once and for all.

**Comment by zarquon42b** [comment]
You mean checking for the appropriate H5Cpp.h as defined by some cmake variables? Yes, this should do the trick, I guess.

**Pull request merged**
